---
title: "Exercise 4"
author: "Angus McKay, Laura Roman, Euan Dowers, Veronika Kyuchukova"
date: "February 21, 2017"
output: pdf_document
---


```{r, eval=TRUE, echo=FALSE}
rm(list = ls())
set.seed(444)

N <- 1000

# Generate a function that returns a solution that gives r for given values of alpha, beta and sigma
CIR_model<- function(alpha, beta, sigma){

  T <- 1
  r0<- 2
  dt <- 1 / N
  d1<-function(x) eval(expression(alpha-beta*x))
  d2<- function(x) eval(expression(sigma*sqrt(x)))
  
  Z<- rnorm(N,0,1)
  r<- numeric(N+1)
 
  sdt<- sqrt(dt)
  r[1]<-r0
  
  for ( i in 2:( N +1)){
    dB<- sdt * Z [i -1]
    r [ i ] <- r [i -1] + d1(r [i -1]) * dt +
      d2(r [i -1]) * dB
  }
  r<-ts(r,start = 0,end = 1, deltat = 1/N)
  return(r)
}



# Assign values to alpha, beta and sigma
alpha <-c(2, 6, 6, 6 , 1, 1,  1,   1)
beta  <-c(2, 2, 5, 1 , 2, 1, 0.1 ,10)
sigma <-c(2, 2, 3, 1 , 1, 1, 3.7, 1)

#Create a matrix where to store the different trajectories that are generated with the different values of the constants
CIR<-matrix(0,length(alpha),N+1)

# Create a loop that assigns to each row of the matrix, the r values over the period for given values of alpha, beta and sigma
for (i in 1:nrow(CIR)){
  set.seed(444)
  CIR[i,]<-CIR_model(alpha[i], beta[i], sigma[i])
}


#Plot the results

plot(CIR[1,], main= "Trajectories of Cox-Ingersoll-Ross process",
     col="red", ylim=c(0,6), xlab="t", ylab="r",type = "l",
     axes=FALSE)
grid(5,5,col="black")
abline(h=0,col="Black",lty=3)
axis(1, at=c(0,1000), labels = c(0,1))
axis(2)
box()

color<-c("red","blue","yellow","purple","black","green", "grey","orange")
for (i in 2:nrow(CIR)){
  lines(CIR[i,], col= color[i])
}


legend("topleft",
       c("alpha=6, beta=1, sigma=1", "alpha=6, beta=2, sigma=2","alpha=6, beta=5, sigma=3",
         "alpha=2, beta=2, sigma=2","alpha=1, beta=1, sigma=1","alpha=1, beta=2, sigma=1",
         "alpha=1, beta=0.1, sigma=3.7","alpha=1, beta=10, sigma=1"),
       col=c("purple", "blue","yellow","red","green","black","grey","orange"),
       lty=c(1,1),
       cex = 0.6,
       bg="white")

```






\newpage
##Appendix
```{r, eval=FALSE}
rm(list = ls())
set.seed(444)

N <- 1000

# Generate a function that returns the r values for given alpha, beta and sigma
CIR_model<- function(alpha, beta, sigma){

  T <- 1
  r0<- 2
  dt <- 1 / N
  d1<-function(x) eval(expression(alpha-beta*x))
  d2<- function(x) eval(expression(sigma*sqrt(x)))
  
  Z<- rnorm(N,0,1)
  r<- numeric(N+1)
 
  sdt<- sqrt(dt)
  r[1]<-r0
  
  for ( i in 2:( N +1)){
    dB<- sdt * Z [i -1]
    r [ i ] <- r [i -1] + d1(r [i -1]) * dt +
      d2(r [i -1]) * dB
  }
  r<-ts(r,start = 0,end = 1, deltat = 1/N)
  return(r)
}



# Assign values to alpha, beta and sigma
alpha <-c(2, 6, 6, 6 , 1, 1,  1,   1)
beta  <-c(2, 2, 5, 1 , 2, 1, 0.1 ,10)
sigma <-c(2, 2, 3, 1 , 1, 1, 3.7, 1)

# Create a matrix to store the trajectories that 
# are generated with the different values of the constants
CIR<-matrix(0,length(alpha),N+1)

# Create a loop that assigns to each row of the matrix, 
# the r values over the period for given values of alpha, beta and sigma
for (i in 1:nrow(CIR)){
  set.seed(444)
  CIR[i,]<-CIR_model(alpha[i], beta[i], sigma[i])
}


#Plot the results

plot(CIR[1,], main= "Trajectories of Cox-Ingersoll-Ross process",
     col="red", ylim=c(0,6), xlab="t", ylab="r",type = "l",
     axes=FALSE)
grid(5,5,col="black")
abline(h=0,col="Black",lty=3)
axis(1, at=c(0,1000), labels = c(0,1))
axis(2)
box()

color<-c("red","blue","yellow","purple","black","green", "grey","orange")
for (i in 2:nrow(CIR)){
  lines(CIR[i,], col= color[i])
}


legend("topleft",
       c("alpha=6, beta=1, sigma=1", "alpha=6, beta=2, sigma=2","alpha=6, beta=5, sigma=3",
         "alpha=2, beta=2, sigma=2","alpha=1, beta=1, sigma=1","alpha=1, beta=2, sigma=1",
         "alpha=1, beta=0.1, sigma=3.7","alpha=1, beta=10, sigma=1"),
       col=c("purple", "blue","yellow","red","green","black","grey","orange"),
       lty=c(1,1),
       cex = 0.6,
       bg="white")

```
